TRAIN_CONFIG = {
    "seed": 42,
    "total_timesteps": 1000000,
    "n_steps": 2048,
    "batch_size": 64,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.2,
    "clip_range_vf": None,
    "normalize_advantage": True,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "use_sde": False,
    "sde_sample_freq": -1,
    "target_kl": None,
    "tensorboard_log": "./tensorboard_logs/",
    "policy_kwargs": None,
    "verbose": 1,
    "checkpoint_freq": 10000,
    "checkpoint_path": "./checkpoints/",
    "log_interval": 5
}